#!/bin/sh

case "$1" in
  configure)
    if ! [ `getent passwd monasca` ]; then
      adduser --system --group monasca
    fi

    #Restart does not pick up upstart job config changes stop/start is needed
    stop monasca-persister
    start monasca-persister
  ;;
esac

exit 0
